import React, { useCallback, useState } from 'react';
import { View, TouchableOpacity, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { useTheme } from '@/src/theme/ThemeProvider';
import { useAuth } from '@/src/auth/AuthProvider';
import { spacing, font, formatMoneyFull, formatMoney } from '@/src/theme/tokens';
import { api } from '@/src/api/client';
import { Screen, Card, H2, Body, Label, Button } from '@/src/components/ui';

function monthLabel(d: Date) {
  return d.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
}

function buildReportHTML(opts: {
  userName: string; currency: string; period: string;
  summary: any; wallets: any[]; txs: any[];
}) {
  const { userName, currency, period, summary, wallets, txs } = opts;
  const fmt = (n: number) => formatMoneyFull(n, currency);

  const catRows = (summary.category_breakdown || []).map((c: any) => `
    <tr><td>${c.category}</td><td style="text-align:right">${fmt(c.amount)}</td></tr>
  `).join('');

  const txRows = txs.slice(0, 40).map((t: any) => `
    <tr>
      <td>${/^\d{4}-\d{2}-\d{2}$/.test(t.date || '') ? new Date(`${t.date}T00:00:00`).toLocaleDateString() : new Date(t.date).toLocaleDateString()}</td>
      <td>${t.category}</td>
      <td>${t.note || ''}</td>
      <td style="text-align:right;color:${t.type === 'income' ? '#059669' : t.type === 'expense' ? '#DC2626' : '#111'}">
        ${t.type === 'income' ? '+' : t.type === 'expense' ? '-' : ''}${fmt(t.amount)}
      </td>
    </tr>
  `).join('');

  const walletRows = wallets.map((w: any) => `
    <tr><td>${w.name}</td><td>${w.type}</td><td style="text-align:right">${fmt(w.balance)}</td></tr>
  `).join('');

  return `
  <html>
  <head>
    <meta charset="utf-8" />
    <style>
      * { font-family: -apple-system, Helvetica, Arial, sans-serif; box-sizing: border-box; }
      body { padding: 32px; color: #111; }
      h1 { font-size: 22px; margin-bottom: 2px; }
      .muted { color: #6B7280; font-size: 12px; }
      .hero { background: #0B0B0F; color: #fff; border-radius: 16px; padding: 24px; margin: 20px 0; }
      .hero .label { color: #9CA3AF; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; }
      .hero .value { font-size: 30px; font-weight: 700; margin-top: 4px; }
      .row { display: flex; gap: 24px; margin-top: 16px; }
      .row .col { flex: 1; }
      .row .col .label { color: #9CA3AF; font-size: 11px; }
      .row .col .value { font-size: 15px; font-weight: 700; margin-top: 2px; }
      h2 { font-size: 15px; margin-top: 28px; margin-bottom: 8px; border-bottom: 1px solid #E5E7EB; padding-bottom: 6px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      td { padding: 6px 4px; border-bottom: 1px solid #F3F4F6; }
      .footer { margin-top: 40px; font-size: 10px; color: #9CA3AF; text-align: center; }
    </style>
  </head>
  <body>
    <h1>Financial Report — ${userName}</h1>
    <div class="muted">${period} · Generated by Wallume</div>

    <div class="hero">
      <div class="label">Net Worth</div>
      <div class="value">${fmt(summary.net_worth ?? 0)}</div>
      <div class="row">
        <div class="col"><div class="label">Income</div><div class="value" style="color:#34D399">+${fmt(summary.month_income ?? 0)}</div></div>
        <div class="col"><div class="label">Expense</div><div class="value" style="color:#F87171">-${fmt(summary.month_expense ?? 0)}</div></div>
        <div class="col"><div class="label">Cash Flow</div><div class="value">${fmt(summary.cash_flow ?? 0)}</div></div>
        <div class="col"><div class="label">Health Score</div><div class="value">${summary.health_score ?? 0}/100</div></div>
      </div>
    </div>

    <h2>Wallets</h2>
    <table>${walletRows || '<tr><td class="muted">No wallets</td></tr>'}</table>

    <h2>Spending by Category</h2>
    <table>${catRows || '<tr><td class="muted">No expenses this month</td></tr>'}</table>

    <h2>Recent Transactions</h2>
    <table>${txRows || '<tr><td class="muted">No transactions</td></tr>'}</table>

    <div class="footer">Wallume — Personal Finance · This report is for personal record-keeping only.</div>
  </body>
  </html>`;
}

export default function ExportReport() {
  const { colors } = useTheme();
  const { user } = useAuth();
  const router = useRouter();
  const [generating, setGenerating] = useState(false);
  const [summary, setSummary] = useState<any>(null);
  const cur = user?.currency || 'USD';

  const load = useCallback(async () => {
    try { setSummary(await api.summary()); } catch {}
  }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));

  const generate = async () => {
    setGenerating(true);
    try {
      const [s, txRes, walletRes] = await Promise.all([api.summary(), api.transactions(), api.wallets()]);
      const html = buildReportHTML({
        userName: user?.name || 'User',
        currency: cur,
        period: monthLabel(new Date()),
        summary: s,
        wallets: walletRes.wallets || [],
        txs: txRes.transactions || [],
      });
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf', dialogTitle: 'Wallume Financial Report' });
      } else {
        Alert.alert('Report ready', `Saved to: ${uri}`);
      }
    } catch (e: any) {
      Alert.alert('Could not generate report', e?.message || 'Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Screen>
      <SafeAreaView style={{ flex: 1 }} edges={['top', 'bottom']}>
        <View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xl, paddingTop: spacing.md }}>
          <TouchableOpacity testID="export-back" onPress={() => router.back()}><Ionicons name="chevron-back" size={24} color={colors.onSurface} /></TouchableOpacity>
          <H2 style={{ marginLeft: spacing.md }}>Export Report</H2>
        </View>

        <View style={{ padding: spacing.xl }}>
          <Card>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
              <View style={{ width: 46, height: 46, borderRadius: 14, backgroundColor: colors.error + '22', alignItems: 'center', justifyContent: 'center' }}>
                <Ionicons name="document-text" size={22} color={colors.error} />
              </View>
              <View style={{ flex: 1 }}>
                <Body style={{ fontFamily: font.textBold }}>{monthLabel(new Date())} Report</Body>
                <Body muted style={{ fontSize: 12, marginTop: 2 }}>
                  Net worth, cash flow, spending by category, and recent transactions.
                </Body>
              </View>
            </View>
          </Card>

          {!!summary && (
            <Card style={{ marginTop: spacing.md }}>
              <Label>Preview</Label>
              <View style={{ marginTop: spacing.sm, gap: 6 }}>
                <Body style={{ fontSize: 13 }}>Net worth: <Body style={{ fontFamily: font.textBold, fontSize: 13 }}>{formatMoney(summary.net_worth ?? 0, cur)}</Body></Body>
                <Body style={{ fontSize: 13 }}>Cash flow: <Body style={{ fontFamily: font.textBold, fontSize: 13 }}>{formatMoney(summary.cash_flow ?? 0, cur)}</Body></Body>
                <Body style={{ fontSize: 13 }}>Health score: <Body style={{ fontFamily: font.textBold, fontSize: 13 }}>{summary.health_score ?? 0}/100</Body></Body>
              </View>
            </Card>
          )}

          <Button
            testID="export-generate-btn"
            label={generating ? 'Generating…' : 'Generate & Share PDF'}
            onPress={generate}
            loading={generating}
            style={{ marginTop: spacing.xl }}
          />
          <Body muted style={{ fontSize: 11, marginTop: spacing.md, textAlign: 'center' }}>
            The PDF is generated on your device and shared directly — nothing is uploaded anywhere.
          </Body>
        </View>
      </SafeAreaView>
    </Screen>
  );
}
